### ISSUE TITLE
寻求帮助

### ISSUE THREAD

**Issue by jinzaizhichi** [yetone/nvim#2]
我安装后出现这个情况，hererocks卡住了，一直停留在安装状态，请帮我一下，谢谢！

**Comment by yetone** [comment]
@jinzaizhichi  已收到，现在有点晚了我准备睡觉了，今天晚上我们可以约个时间我可以帮你远程看一下

**Comment by watsy0007** [comment]
？？？why close?

**Comment by yetone** [comment]
@watsy0007 No reply

**Comment by watsy0007** [comment]
ok

**Comment by yetone** [comment]
@jinzaizhichi @watsy0007 这个问题已经修复
